---
name: Run tests

on:
  push:
  pull_request:
    branches: [$default-branch]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Checkout fuzzback
        uses: actions/checkout@v3

      - name: Checkout fzf
        uses: actions/checkout@v3
        with:
          repository: junegunn/fzf
          path: fzf

      - name: Install dependencies
        run: sudo apt-get install -y expect vim wget tar tmux

      - name: Install latest fzf
        working-directory: fzf
        run: ./install --all

      - name: Run tests in isolation
        run: tests/run_tests_in_isolation

